"""Builds src/captures.ts from the raw outputs capture.sh saved in the harness.
Lines stay verbatim: tool output is cut with "…", prose answers are wrapped."""
import json, sys, textwrap
S = sys.argv[1]
W = 96
def rd(n): return open(f'{S}/{n}.out').read().splitlines()
def cmd(n): return open(f'{S}/{n}.cmd').read()
def cut(l): return l if len(l) <= W else l[:W - 1] + '…'
def wrap(l): return textwrap.wrap(l, W, subsequent_indent='  ' if l.startswith('- ') else '') or ['']
def grep(lines, subs): return [cut(l) for l in lines if any(s in l for s in subs)]
m, i, s = rd('01-market'), rd('02-install'), rd('03-setup')
ask = rd('05-ask'); run = rd('08-run'); gain = rd('12-gain')
data = {
  'install': [
    {'cmd': cmd('01-market'), 'out': [cut(m[-1])]},
    {'cmd': cmd('02-install'), 'out': [cut(i[-1].split('...')[-1])]},
    {'cmd': cmd('03-setup'), 'out': [cut(s[0])] + grep(s, ['Installed deterministic runner', 'Installed DeepSeek backend', 'Installed Antigravity backend', 'Installed Codex backend', 'Installed OpenCode backend', 'Installed GitHub Copilot backend'])},
  ],
  'doctor': [{'cmd': cmd('04-doctor'), 'out': [cut(l) for l in rd('04-doctor')[3:9]]}],
  'ask': [{'cmd': cmd('05-ask'), 'out': [cut(l) for l in ask if l.startswith(('cx-stream', '  sandbox'))] + [''] + [w for l in ask if l.startswith('`git worktree') for w in wrap(l)]}],
  'agent': [
    {'cmd': cmd('06-agent'), 'out': [w for l in rd('06-agent') if l.strip() for w in wrap(l)]},
    {'cmd': cmd('07-test'), 'out': rd('07-test')},
  ],
  'run': [{'cmd': cmd('08-run'), 'out': [cut(run[0]), cut(run[1]), '  …'] + [cut(l) for l in run[-4:]]}],
  'sessions': [
    {'cmd': cmd('09-sessions'), 'out': [cut(l) for l in rd('09-sessions')[:6]]},
    {'cmd': cmd('11-resume'), 'out': [cut(rd('11-resume')[-1])]},
  ],
  'gain': [
    {'cmd': cmd('12-gain'), 'out': [cut(l) for l in gain[3:10]] + [cut(gain[-1])]},
    {'cmd': cmd('13-clean'), 'out': [cut(l) for l in rd('13-clean')[-2:]]},
  ],
  'help': [{'cmd': cmd('14-help'), 'out': rd('14-help')[:22]}],
}
with open('src/captures.ts', 'w') as f:
  f.write('// Real outputs captured in the sandbox-harness container by ../capture.sh (cli-dispatch 6.0.1),\n'
          '// generated by ../gen-captures.py. Lines are verbatim; long lines are cut with "…" or wrapped.\n'
          'export const captures = ' + json.dumps(data, ensure_ascii=False, indent=1) + ' as const;\n')
for k, v in data.items():
  print('##', k)
  for c in v:
    print('>', c['cmd'])
    for l in c['out']: print('  ', l)
