// Real outputs captured in the sandbox-harness container by ../capture.sh (cli-dispatch 6.0.1),
// generated by ../gen-captures.py. Lines are verbatim; long lines are cut with "…" or wrapped.
export const captures = {
 "install": [
  {
   "cmd": "/plugin marketplace add rbinar/cli-dispatch",
   "out": [
    "✔ Successfully added marketplace: cli-dispatch (declared in user settings)"
   ]
  },
  {
   "cmd": "/plugin install cli-dispatch@cli-dispatch",
   "out": [
    "✔ Successfully installed plugin: cli-dispatch@cli-dispatch (scope: user)"
   ]
  },
  {
   "cmd": "/cli-dispatch:setup",
   "out": [
    "Backends: deepseek,antigravity,codex,opencode,copilot",
    "Installed deterministic runner -> cli-dispatch-run (+ per-backend worktree runners, verdict eng…",
    "Installed DeepSeek backend -> claude-ds, claude-ds-stream, ds-agent (parser -> /tmp/demohome/.l…",
    "Installed Antigravity backend -> ag-stream, ag-agent (parser -> /tmp/demohome/.local/share/cli-…",
    "Installed Codex backend -> cx-stream, cx-agent (parser -> /tmp/demohome/.local/share/cli-dispat…",
    "Installed OpenCode backend -> oc-stream, oc-agent (parser -> /tmp/demohome/.local/share/cli-dis…",
    "Installed GitHub Copilot backend -> cp-stream, cp-agent (parser -> /tmp/demohome/.local/share/c…"
   ]
  }
 ],
 "doctor": [
  {
   "cmd": "/cli-dispatch:doctor cx",
   "out": [
    "── Codex / OpenAI ─────────── optional ─────────────────",
    "  ✓ cx-agent on PATH",
    "  ✓ cx-stream on PATH (/home/dev/.local/bin/cx-stream)",
    "  ✓ codex CLI found (codex-cli 0.160.0)",
    "  ✓ logged in via codex login (ChatGPT)",
    "  – model: CX_MODEL not set (codex default used)"
   ]
  }
 ],
 "ask": [
  {
   "cmd": "/cli-dispatch:ask cx \"In one sentence: what does git worktree add do?\"",
   "out": [
    "cx-stream → Codex (OpenAI Codex CLI) worker",
    "  sandbox: read-only",
    "",
    "`git worktree add` creates another working directory for the same repository, letting you work",
    "on a different branch without switching branches in your current directory."
   ]
  }
 ],
 "agent": [
  {
   "cmd": "add() in math.mjs is broken. Delegate the fix to DeepSeek, verify with node --test, then apply the patch.",
   "out": [
    "I fixed `add()` in `math.mjs`. It was subtracting, and now returns `a + b`.",
    "- DeepSeek made the change and its `node --test` check passed.",
    "- I reviewed its one-line patch and applied it here.",
    "- I ran `node --test` myself: 1 passed, 0 failed.",
    "- DeepSeek's worktree is still at `/tmp/ds-wt-JQg7xn`. `/cli-dispatch:clean` will remove it.",
    "- Nothing is committed yet."
   ]
  },
  {
   "cmd": "node --test",
   "out": [
    "# tests 1",
    "# pass 1",
    "# fail 0"
   ]
  }
 ],
 "run": [
  {
   "cmd": "/cli-dispatch:run cx \"Fix add() in math.mjs\" --verify 'node --test'",
   "out": [
    "Preparing worktree (new branch 'cx-run-1791284403-77035')",
    "cx-stream → Codex (OpenAI Codex CLI) worker",
    "  …",
    "exit: 0  session: 01a110de-dd37-7702-bf93-95c1c658b8d4  state: done  verify: pass",
    "diff: 1 file changed, 1 insertion(+), 1 deletion(-)",
    "STRANDED changes in worktree: /tmp/cx-wt-N3ExH2",
    "patch: /home/dev/.cache/cli-dispatch/sessions/01a110de-dd37-7702-bf93-95c1c658b8d4/verdict-diff…"
   ]
  }
 ],
 "sessions": [
  {
   "cmd": "/cli-dispatch:sessions",
   "out": [
    "done     codex       01a110de-dd37-7702-bf93-95c1c658b8d4  2026-10-06T11:00:03.479Z",
    "         cwd: /tmp/cx-wt-N3ExH2",
    "         \"Fix add() in math.mjs so it returns the sum. Change nothing \"",
    "done     deepseek    a84ae3a0-6edb-4705-a56c-47ca4101b45f  2026-10-06T10:59:38.875Z",
    "         cwd: /tmp/ds-wt-JQg7xn",
    "         \"In math.mjs, add(a, b) returns a - b; it should return a + b\""
   ]
  },
  {
   "cmd": "/cli-dispatch:resume 01a110de… \"Which file did you change? One line.\"",
   "out": [
    "Changed `math.mjs` and created the required `worker-report.json`."
   ]
  }
 ],
 "gain": [
  {
   "cmd": "/cli-dispatch:gain",
   "out": [
    "backend       sessions       input      output    no data",
    "------------ -------- ------------ ------------ ----------",
    "antigravity        13            0            0         13",
    "codex               8       30,328        3,229          0",
    "copilot             6            0            0          6",
    "deepseek           19      229,080      107,207          2",
    "opencode            5       55,869        2,100          0",
    "deterministic runs (verdict.json present): 28  |  verify ✓ 25 · ✗ 3 · none 0"
   ]
  },
  {
   "cmd": "/cli-dispatch:clean",
   "out": [
    "stale (running but dead, idle > 600s): 0",
    "nothing to clean."
   ]
  }
 ],
 "help": [
  {
   "cmd": "/cli-dispatch:help",
   "out": [
    "┌─ cli-dispatch ───────────────────────────────────────────────────────────────┐",
    "│                                                                              │",
    "│  SETUP & HEALTH                                                              │",
    "│    /cli-dispatch:setup          Install & configure worker backends          │",
    "│    /cli-dispatch:doctor [be]    Health check — PATH, keys, auth, models      │",
    "│                                                                              │",
    "│  DELEGATE                                                                    │",
    "│    /cli-dispatch:run <be> \"<task>\" --verify '<cmd>'   Deterministic runner   │",
    "│    /cli-dispatch:ask <be> \"<prompt>\"   One-shot answer, no repo changes      │",
    "│                                                                              │",
    "│  MONITOR                                                                     │",
    "│    /cli-dispatch:sessions [be]  List sessions (all backends, or one)         │",
    "│    /cli-dispatch:watch <id>     Live status; --wait blocks until done        │",
    "│    /cli-dispatch:resume <id> …  Continue a session with a follow-up          │",
    "│    /cli-dispatch:kill <id>      Stop a running worker session                │",
    "│                                                                              │",
    "│  USAGE & HOUSEKEEPING                                                        │",
    "│    /cli-dispatch:balance [be]   Usage / credits (all backends, or one)       │",
    "│    /cli-dispatch:gain           Token totals; --drift for delegation drift   │",
    "│    /cli-dispatch:clean          Remove old sessions; --schedule: daily job   │",
    "│    /cli-dispatch:help           This reference                               │",
    "│                                                                              │"
   ]
  }
 ]
} as const;
